info:
  contact: {}
  license: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: 验证用户登录是否成功
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"errcode":"200","data":"[{"expId":"111","expName":"TensorFlow","expType":"TensorFlow","expTrade":"制造业","expScene":"零售","expRemark":"零售零售零售零售","expDeg":"2","expCreateUser":"tfg"}]","msg":""}'
          schema:
            type: string
        "400":
          description: '{"errcode":"400","data":"","msg":"error......"}'
          schema:
            type: string
      summary: 登录
      tags:
      - 用户信息
swagger: "2.0"
