info:
  contact: {}
  license: {}
paths:
  /getCSRF:
    get:
      description: 用户第一次访问后端服务器时，需要获取 CSRF Token
      produces:
      - application/json
      responses:
        "200":
          description: '{"Message": "CSRF token is in response header"}'
          schema:
            type: string
      summary: 获取 CSRF Token
      tags:
      - 验证
  /login:
    get:
      consumes:
      - application/json
      description: 验证用户登录是否成功
      parameters:
      - description: X-CSRF-TOKEN
        in: header
        name: csrf-token
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"errcode":"200","data":"[{"expId":"111","expName":"TensorFlow","expType":"TensorFlow","expTrade":"制造业","expScene":"零售","expRemark":"零售零售零售零售","expDeg":"2","expCreateUser":"tfg"}]","msg":""}'
          schema:
            type: string
        "400":
          description: '{"errcode":"400","data":"","msg":"error......"}'
          schema:
            type: string
      security:
      - csrf-token: []
      summary: 登录
      tags:
      - 用户信息
swagger: "2.0"
